export { ToJsonProperties, ToJsonProperty } from '@src/api/entities/interfaces/ToJsonProperties'
export { ColorResolvable } from '@src/api/entities/interfaces/ColorResolvable'
export { Resolvable } from '@src/api/entities/interfaces/Resolvable'
export { EntityKey } from '@src/api/entities/interfaces/EntityKey'
export { Json } from '@src/api/entities/interfaces/Json'
