export enum MessageTypes {
    Default = 0,
    RecipientAdd = 1,
    RecipientRemove = 2,
    Call = 3,
    ChannelNameChange = 4,
    ChannelIconChange = 5,
    ChannelPinnedMessage = 6,
    GuildMemberJoin = 7,
    UserPremiumGuildSubscription = 8,
    UserPremiumGuildSubscriptionTier1 = 9,
    UserPremiumGuildSubscriptionTier2 = 10,
    UserPremiumGuildSubscriptionTier3 = 11,
    ChannelFollowAdd = 12,
    GuildDiscoveryDisqualified = 13,
    GuildDiscoveryRequalified = 14,
    GuildDiscoveryGracePeriodInitialWarning = 15,
    GuildDiscoveryGracePeriodFinalWarning = 16,
    ThreadCreated = 17,
    Reply = 18,
    ChatInputCommand = 19,
    ThreadStarterMessage = 20,
    GuildInviteReminder = 21,
    ContextMenuCommand = 22
}
