export enum GuildSystemChannelFlags {
  SUPPRESS_JOIN_NOTIFICATIONS = 1 << 0,
  SUPPRESS_PREMIUM_SUBSCRIPTIONS = 1 << 1,
  SUPRESS_GUILD_REMINDER_NOTIFICATIONS = 1 << 2,
  SUPRESS_JOIN_NOTIFICATION_REPLIES = 1 << 3
}